---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: 405834051687.dkr.ecr.us-east-1.amazonaws.com/apigatewayservice:4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "80"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://dashboard-eureka-server:8761/eureka/"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-server-local:8888"
        - name: SPRING_CLOUD_CONFIG_FAIL_FAST
          value: "false"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "api-gateway-service"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "false"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "true"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "true"
        - name: EUREKA_CLIENT_HEALTHCHECK_ENABLED
          value: "true"
        - name: EUREKA_INSTANCE_INSTANCE_ID
          value: "api-gateway-service:api-gateway-service-application:80"
        - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
          value: "10"
        - name: EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS
          value: "90"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis"
        - name: SPRING_DATA_REDIS_PORT
          value: "6379"
        - name: KEYCLOAK_JWK_SET_URI
          value: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
        - name: MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          value: "file:/config/"
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: gateway-config
          mountPath: /config
          readOnly: true
      volumes:
      - name: gateway-config
        configMap:
          name: api-gateway-k8s-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: project-ms-public-lb
spec:
  type: LoadBalancer
  selector:
    app: api-gateway-service
  ports:
  - name: http
    port: 80
    targetPort: 80
