---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server-config
data:
  application.properties: |
    spring.cloud.config.enabled=false
    spring.cloud.service-registry.auto-registration.enabled=false
    eureka.client.register-with-eureka=false
    eureka.client.fetch-registry=false
    eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
    eureka.server.enable-self-preservation=false
    eureka.instance.hostname=dashboard-eureka-server
