---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-service
  template:
    metadata:
      labels:
        app: fraud-service
    spec:
      containers:
      - name: fraud-service
        image: 405834051687.dkr.ecr.us-east-1.amazonaws.com/fraudservice:3
        imagePullPolicy: Always
        ports:
        - containerPort: 9593
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "9593"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://dashboard-eureka-server:8761/eureka/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "fraud-service"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "false"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "true"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "true"
        - name: EUREKA_CLIENT_HEALTHCHECK_ENABLED
          value: "true"
        - name: EUREKA_INSTANCE_INSTANCE_ID
          value: "fraud-service:fraud-service-application:9593"
        - name: EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS
          value: "10"
        - name: EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS
          value: "90"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config-server-local:8888"
        - name: SPRING_CLOUD_CONFIG_FAIL_FAST
          value: "false"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "redpanda:9092"
        - name: MANAGEMENT_HEALTH_KAFKA_ENABLED
          value: "false"
        livenessProbe:
          tcpSocket:
            port: 9593
          initialDelaySeconds: 45
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 9593
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-service
spec:
  type: ClusterIP
  selector:
    app: fraud-service
  ports:
  - name: http
    port: 9593
    targetPort: 9593
